// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxsogkmnimaihoxbpnpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54c29na21uaW1haWhveGJwbnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjEyNjYsImV4cCI6MjA3MDA5NzI2Nn0.YNVtsAlU1Ss91vXGFRfi9DaCn50C1iEElp_osFlmpxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});